# Generated by Django 3.0.1 on 2019-12-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=120)),
                ('CustomerAge', models.IntegerField(max_length=100)),
            ],
        ),
    ]
